version: '3.6'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - app-network
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8094:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:password@postgres:5432/test
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # enables the console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - app-network
networks:
    app-network:
      driver: bridge
volumes:
  postgres_data: